### ISSUE TITLE
getting angular version issue

### ISSUE THREAD

**Issue by Grv90** [ocombe/i18n-demo-no-cli#1]
Getting this issue while extracting :(
"angular/common": "~5.0.0",
    "angular/compiler": "~5.0.0",
    "angular/core": "~5.0.0",
    "angular/forms": "~5.0.0",
  "angular/cli": "^1.5.4",
   "angular/compiler-cli": "~5.0.0", 
```
Error: Please update @angular/cli. Angular 5+ requires at least Angular CLI 1.5+
    at throwNotSupportedError (C:\Trunk\WebClientNew\node_modules\@angular\compiler-cli\src\ngtools_api.js:78:11)
    at Function.NgTools_InternalApi_NG_2.extractI18n (C:\Trunk\WebClientNew\node_modules\@angular\compiler-cli\src\ngtools_api.js:72:15)
    at _donePromise.Promise.resolve.then (C:\Trunk\WebClientNew\node_modules\@ngtools\webpack\src\extract_i18n_plugin.js:117:58)
```

**Comment by HichamBI** [comment]
I have the same issue when update to Angular 5.0.0 and Angular/CLI 1.5.0.

**Comment by maximilianochs** [comment]
Same issue here. The method in angular/compiler-cli that is used by ExtractI18nPlugin has been removed and throws this error. 

@ocombe do you know a way to extract i18n with angular 5.X without using angular-cli? The angular docs still describe ExtractI18nPlugin as alternative: https://angular.io/guide/i18n

**Comment by ocombe** [comment]
Hello, I've updated the webpack config to support the new versions of the cli, it should work fine now!
You were right, extraction is done via `AngularCompilerPlugin` now, instead of `ExtractI18nPlugin` which isn't compatible with v5+ anymore. I'll update the Angular docs as well.
